SET DEFINE OFF;
Insert into HR.JOB_HISTORY
   (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
 Values
   (102, TO_DATE('1/13/2001', 'MM/DD/YYYY'), TO_DATE('7/24/2006', 'MM/DD/YYYY'), 'IT_PROG', 60);
Insert into HR.JOB_HISTORY
   (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
 Values
   (101, TO_DATE('9/21/1997', 'MM/DD/YYYY'), TO_DATE('10/27/2001', 'MM/DD/YYYY'), 'AC_ACCOUNT', 110);
Insert into HR.JOB_HISTORY
   (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
 Values
   (101, TO_DATE('10/28/2001', 'MM/DD/YYYY'), TO_DATE('3/15/2005', 'MM/DD/YYYY'), 'AC_MGR', 110);
Insert into HR.JOB_HISTORY
   (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
 Values
   (201, TO_DATE('2/17/2004', 'MM/DD/YYYY'), TO_DATE('12/19/2007', 'MM/DD/YYYY'), 'MK_REP', 20);
Insert into HR.JOB_HISTORY
   (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
 Values
   (114, TO_DATE('3/24/2006', 'MM/DD/YYYY'), TO_DATE('12/31/2007', 'MM/DD/YYYY'), 'ST_CLERK', 50);
Insert into HR.JOB_HISTORY
   (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
 Values
   (122, TO_DATE('1/1/2007', 'MM/DD/YYYY'), TO_DATE('12/31/2007', 'MM/DD/YYYY'), 'ST_CLERK', 50);
Insert into HR.JOB_HISTORY
   (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
 Values
   (200, TO_DATE('9/17/1995', 'MM/DD/YYYY'), TO_DATE('6/17/2001', 'MM/DD/YYYY'), 'AD_ASST', 90);
Insert into HR.JOB_HISTORY
   (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
 Values
   (176, TO_DATE('3/24/2006', 'MM/DD/YYYY'), TO_DATE('12/31/2006', 'MM/DD/YYYY'), 'SA_REP', 80);
Insert into HR.JOB_HISTORY
   (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
 Values
   (176, TO_DATE('1/1/2007', 'MM/DD/YYYY'), TO_DATE('12/31/2007', 'MM/DD/YYYY'), 'SA_MAN', 80);
Insert into HR.JOB_HISTORY
   (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID)
 Values
   (200, TO_DATE('7/1/2002', 'MM/DD/YYYY'), TO_DATE('12/31/2006', 'MM/DD/YYYY'), 'AC_ACCOUNT', 90);
COMMIT;
